### ISSUE TITLE
Broke with 7.0.0 update

### ISSUE THREAD

**Issue by MrTyton** [pmrowla/streamlink-plugins#27]
The update to streamlink 7.0.0 seems to have broken this plugin.

```
[session][error] Failed to load plugin eplus from C:\Program Files\Streamlink\pkgs\streamlink\plugin\api\__init__.py
Traceback (most recent call last):
  File "C:\Program Files\Streamlink\pkgs\streamlink\session\plugins.py", line 200, in _load_plugin_from_finder
    mod = exec_module(finder, f"streamlink.plugins.{name}", override=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Streamlink\pkgs\streamlink\utils\module.py", line 45, in exec_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\NAME\AppData\Roaming\streamlink\plugins\eplus.py", line 15, in <module>
    from streamlink.plugin.api import validate, useragents, HTTPSession
ImportError: cannot import name 'HTTPSession' from 'streamlink.plugin.api' (C:\Program Files\Streamlink\pkgs\streamlink\plugin\api\__init__.py)
usage: streamlink [OPTIONS] <URL> [STREAM]

Use -h/--help to see the available options or read the manual at https://streamlink.github.io/
```

**Comment by MrTyton** [comment]
Updating to the newer version helped, guess I just had an old copy. Apologies.
